version: "3"

services:
    mysql:
        image: mariadb:10.5.8
        ports:
            - "4306:3306"
        volumes:
            - ../../../mysql/acod:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: acod
            MYSQL_USER: uhorn
            MYSQL_PASSWORD: password

    wordpress:
        depends_on:
            - mysql
        image: wordpress:latest
        ports:
            - "8088:80"
        volumes:
            - ../../../wp-content:/var/www/html/wp-content
            - ../../../uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: uhorn
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: acod
volumes:
    mysql: {}
